#/*-------------------------------------------------------------------
#Author: Aaron Anthony Valoroso
#Date: March 3rd, 2018
#License: BSD-3-Clause
#Email: valoroso99@gmail.com
#--------------------------------------------------------------------*/

Game: Utilities.o
	c++ Utilities.o main.cpp

Utilities.o: Utilities.cpp Utilities.h
	c++ -c  Utilities.cpp
		
clean:
	rm *.o *.out
